/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as PaymentResultRouteImport } from './routes/payment-result'
import { Route as PsicologaIquiqueRouteImport } from './routes/psicologa-iquique'
import { Route as SobrePamelaRayenRouteImport } from './routes/sobre-pamela-rayen'
import { Route as AuthForgotPasswordRouteImport } from './routes/_auth/forgot-password'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AuthRegisterRouteImport } from './routes/_auth/register'
import { Route as AuthResetPasswordRouteImport } from './routes/_auth/reset-password'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCoursesCourseIdRouteImport } from './routes/_authenticated/courses/$courseId'
import { Route as AuthenticatedDashboardIndexRouteImport } from './routes/_authenticated/dashboard/index'
import { Route as AuthenticatedDashboardAdminRouteImport } from './routes/_authenticated/dashboard/admin'
import { Route as AuthenticatedDashboardAdminIndexRouteImport } from './routes/_authenticated/dashboard/admin/index'
import { Route as AuthenticatedDashboardAdminCoursesRouteImport } from './routes/_authenticated/dashboard/admin/courses'
import { Route as AuthenticatedDashboardAdminPaymentsRouteImport } from './routes/_authenticated/dashboard/admin/payments'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const PaymentResultRoute = PaymentResultRouteImport.update({
  id: '/payment-result',
  path: '/payment-result',
  getParentRoute: () => rootRouteImport,
} as any)
const PsicologaIquiqueRoute = PsicologaIquiqueRouteImport.update({
  id: '/psicologa-iquique',
  path: '/psicologa-iquique',
  getParentRoute: () => rootRouteImport,
} as any)
const SobrePamelaRayenRoute = SobrePamelaRayenRouteImport.update({
  id: '/sobre-pamela-rayen',
  path: '/sobre-pamela-rayen',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AuthRoute,
} as any)
const AuthResetPasswordRoute = AuthResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => AuthRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCoursesCourseIdRoute =
  AuthenticatedCoursesCourseIdRouteImport.update({
    id: '/courses/$courseId',
    path: '/courses/$courseId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDashboardIndexRoute =
  AuthenticatedDashboardIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdminRoute =
  AuthenticatedDashboardAdminRouteImport.update({
    id: '/admin',
    path: '/admin',
    getParentRoute: () => AuthenticatedDashboardRoute,
  } as any)
const AuthenticatedDashboardAdminIndexRoute =
  AuthenticatedDashboardAdminIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardAdminCoursesRoute =
  AuthenticatedDashboardAdminCoursesRouteImport.update({
    id: '/courses',
    path: '/courses',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)
const AuthenticatedDashboardAdminPaymentsRoute =
  AuthenticatedDashboardAdminPaymentsRouteImport.update({
    id: '/payments',
    path: '/payments',
    getParentRoute: () => AuthenticatedDashboardAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/payment-result': typeof PaymentResultRoute
  '/psicologa-iquique': typeof PsicologaIquiqueRoute
  '/sobre-pamela-rayen': typeof SobrePamelaRayenRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/courses/$courseId': typeof AuthenticatedCoursesCourseIdRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminRouteWithChildren
  '/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/admin/courses': typeof AuthenticatedDashboardAdminCoursesRoute
  '/dashboard/admin/payments': typeof AuthenticatedDashboardAdminPaymentsRoute
  '/dashboard/admin/': typeof AuthenticatedDashboardAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/payment-result': typeof PaymentResultRoute
  '/psicologa-iquique': typeof PsicologaIquiqueRoute
  '/sobre-pamela-rayen': typeof SobrePamelaRayenRoute
  '/forgot-password': typeof AuthForgotPasswordRoute
  '/login': typeof AuthLoginRoute
  '/register': typeof AuthRegisterRoute
  '/reset-password': typeof AuthResetPasswordRoute
  '/courses/$courseId': typeof AuthenticatedCoursesCourseIdRoute
  '/dashboard': typeof AuthenticatedDashboardIndexRoute
  '/dashboard/admin/courses': typeof AuthenticatedDashboardAdminCoursesRoute
  '/dashboard/admin/payments': typeof AuthenticatedDashboardAdminPaymentsRoute
  '/dashboard/admin': typeof AuthenticatedDashboardAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/payment-result': typeof PaymentResultRoute
  '/psicologa-iquique': typeof PsicologaIquiqueRoute
  '/sobre-pamela-rayen': typeof SobrePamelaRayenRoute
  '/_auth/forgot-password': typeof AuthForgotPasswordRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_auth/register': typeof AuthRegisterRoute
  '/_auth/reset-password': typeof AuthResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRouteWithChildren
  '/_authenticated/courses/$courseId': typeof AuthenticatedCoursesCourseIdRoute
  '/_authenticated/dashboard/admin': typeof AuthenticatedDashboardAdminRouteWithChildren
  '/_authenticated/dashboard/': typeof AuthenticatedDashboardIndexRoute
  '/_authenticated/dashboard/admin/courses': typeof AuthenticatedDashboardAdminCoursesRoute
  '/_authenticated/dashboard/admin/payments': typeof AuthenticatedDashboardAdminPaymentsRoute
  '/_authenticated/dashboard/admin/': typeof AuthenticatedDashboardAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/payment-result'
    | '/psicologa-iquique'
    | '/sobre-pamela-rayen'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/dashboard'
    | '/courses/$courseId'
    | '/dashboard/admin'
    | '/dashboard/'
    | '/dashboard/admin/courses'
    | '/dashboard/admin/payments'
    | '/dashboard/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/payment-result'
    | '/psicologa-iquique'
    | '/sobre-pamela-rayen'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/reset-password'
    | '/courses/$courseId'
    | '/dashboard'
    | '/dashboard/admin/courses'
    | '/dashboard/admin/payments'
    | '/dashboard/admin'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/_authenticated'
    | '/payment-result'
    | '/psicologa-iquique'
    | '/sobre-pamela-rayen'
    | '/_auth/forgot-password'
    | '/_auth/login'
    | '/_auth/register'
    | '/_auth/reset-password'
    | '/_authenticated/dashboard'
    | '/_authenticated/courses/$courseId'
    | '/_authenticated/dashboard/admin'
    | '/_authenticated/dashboard/'
    | '/_authenticated/dashboard/admin/courses'
    | '/_authenticated/dashboard/admin/payments'
    | '/_authenticated/dashboard/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PaymentResultRoute: typeof PaymentResultRoute
  PsicologaIquiqueRoute: typeof PsicologaIquiqueRoute
  SobrePamelaRayenRoute: typeof SobrePamelaRayenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/payment-result': {
      id: '/payment-result'
      path: '/payment-result'
      fullPath: '/payment-result'
      preLoaderRoute: typeof PaymentResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/psicologa-iquique': {
      id: '/psicologa-iquique'
      path: '/psicologa-iquique'
      fullPath: '/psicologa-iquique'
      preLoaderRoute: typeof PsicologaIquiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre-pamela-rayen': {
      id: '/sobre-pamela-rayen'
      path: '/sobre-pamela-rayen'
      fullPath: '/sobre-pamela-rayen'
      preLoaderRoute: typeof SobrePamelaRayenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/forgot-password': {
      id: '/_auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/register': {
      id: '/_auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/reset-password': {
      id: '/_auth/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof AuthResetPasswordRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/courses/$courseId': {
      id: '/_authenticated/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard/': {
      id: '/_authenticated/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof AuthenticatedDashboardIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/admin': {
      id: '/_authenticated/dashboard/admin'
      path: '/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof AuthenticatedDashboardAdminRouteImport
      parentRoute: typeof AuthenticatedDashboardRoute
    }
    '/_authenticated/dashboard/admin/': {
      id: '/_authenticated/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof AuthenticatedDashboardAdminIndexRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
    '/_authenticated/dashboard/admin/courses': {
      id: '/_authenticated/dashboard/admin/courses'
      path: '/courses'
      fullPath: '/dashboard/admin/courses'
      preLoaderRoute: typeof AuthenticatedDashboardAdminCoursesRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
    '/_authenticated/dashboard/admin/payments': {
      id: '/_authenticated/dashboard/admin/payments'
      path: '/payments'
      fullPath: '/dashboard/admin/payments'
      preLoaderRoute: typeof AuthenticatedDashboardAdminPaymentsRouteImport
      parentRoute: typeof AuthenticatedDashboardAdminRoute
    }
  }
}

interface AuthRouteChildren {
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthResetPasswordRoute: typeof AuthResetPasswordRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthResetPasswordRoute: AuthResetPasswordRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface AuthenticatedDashboardAdminRouteChildren {
  AuthenticatedDashboardAdminCoursesRoute: typeof AuthenticatedDashboardAdminCoursesRoute
  AuthenticatedDashboardAdminPaymentsRoute: typeof AuthenticatedDashboardAdminPaymentsRoute
  AuthenticatedDashboardAdminIndexRoute: typeof AuthenticatedDashboardAdminIndexRoute
}

const AuthenticatedDashboardAdminRouteChildren: AuthenticatedDashboardAdminRouteChildren =
  {
    AuthenticatedDashboardAdminCoursesRoute:
      AuthenticatedDashboardAdminCoursesRoute,
    AuthenticatedDashboardAdminPaymentsRoute:
      AuthenticatedDashboardAdminPaymentsRoute,
    AuthenticatedDashboardAdminIndexRoute:
      AuthenticatedDashboardAdminIndexRoute,
  }

const AuthenticatedDashboardAdminRouteWithChildren =
  AuthenticatedDashboardAdminRoute._addFileChildren(
    AuthenticatedDashboardAdminRouteChildren,
  )

interface AuthenticatedDashboardRouteChildren {
  AuthenticatedDashboardAdminRoute: typeof AuthenticatedDashboardAdminRouteWithChildren
  AuthenticatedDashboardIndexRoute: typeof AuthenticatedDashboardIndexRoute
}

const AuthenticatedDashboardRouteChildren: AuthenticatedDashboardRouteChildren =
  {
    AuthenticatedDashboardAdminRoute:
      AuthenticatedDashboardAdminRouteWithChildren,
    AuthenticatedDashboardIndexRoute: AuthenticatedDashboardIndexRoute,
  }

const AuthenticatedDashboardRouteWithChildren =
  AuthenticatedDashboardRoute._addFileChildren(
    AuthenticatedDashboardRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRouteWithChildren
  AuthenticatedCoursesCourseIdRoute: typeof AuthenticatedCoursesCourseIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRouteWithChildren,
  AuthenticatedCoursesCourseIdRoute: AuthenticatedCoursesCourseIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PaymentResultRoute: PaymentResultRoute,
  PsicologaIquiqueRoute: PsicologaIquiqueRoute,
  SobrePamelaRayenRoute: SobrePamelaRayenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
